name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues and this has not been requested before
          required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Is your feature request related to a problem? Describe it.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've thought about.
